### POST

POST localhost:8080/residents/5/birth
Content-Type: application/json

{
  "target_serial_number": 8,
  "report_qualifications_code": "모",
  "phone_number": "010-1234-9876"
}

### PUT
PUT localhost:8080/residents/5/birth/8
Content-Type: application/json

{
  "report_qualifications_code": "모",
  "email_address": "nhn@academy.com",
  "phone_number": "010-1234-5678"
}

### DELETE
DELETE localhost:8080/residents/5/birth/8